In [1]:
#import libraraies
import requests
import pandas as pd
import time

In [8]:
#Keys
API_key = 'AIzaSyBZsUNTO5JKdMTFisA9Jcz9HBTvu1C0VL8'
Channel_ID = 'UCW8Ews7tdKKkBT6GdtQaXvQ'

In [9]:
#API call
pageToken = ''
url = 'https://www.googleapis.com/youtube/v3/search?key='+API_key+'&channelId='+Channel_ID+'&part=snippet,id&order=date&maxResults=100'+pageToken

response = requests.get(url).json()

In [12]:
response['items'][0]

{'etag': 'BdQq8d0hljfXZeIGjJIISfivcNg',
 'id': {'kind': 'youtube#video', 'videoId': 'PlpUo6bHsBQ'},
 'kind': 'youtube#searchResult',
 'snippet': {'channelId': 'UCW8Ews7tdKKkBT6GdtQaXvQ',
  'channelTitle': 'Nate at StrataScratch',
  'description': 'This advanced SQL question is from the Facebook data science interview that tests your ability to write window functions and rank data and use some advanced ...',
  'liveBroadcastContent': 'none',
  'publishTime': '2021-08-09T02:18:01Z',
  'publishedAt': '2021-08-09T02:18:01Z',
  'thumbnails': {'default': {'height': 90,
    'url': 'https://i.ytimg.com/vi/PlpUo6bHsBQ/default.jpg',
    'width': 120},
   'high': {'height': 360,
    'url': 'https://i.ytimg.com/vi/PlpUo6bHsBQ/hqdefault.jpg',
    'width': 480},
   'medium': {'height': 180,
    'url': 'https://i.ytimg.com/vi/PlpUo6bHsBQ/mqdefault.jpg',
    'width': 320}},
  'title': 'Advanced Facebook Data Science SQL interview question [RANK()]'}}

In [20]:
df = pd.DataFrame(columns=["video_id", "video_title", "upload_date"])

In [26]:
for video in response['items']:
  if video['id']['kind'] == 'youtube#video':

    video_id = video['id']['videoId']
    video_title = video['snippet']['title']
    upload_date = video['snippet']['publishedAt']
    
    df = df.append({'video_id':video_id,
                    'video_title':video_title,
                    'upload_data':upload_date},
                    ignore_index= True)

In [27]:
df

       video_id  ...           upload_data
0   PlpUo6bHsBQ  ...  2021-08-09T02:18:01Z
1   uY2wfR8Dkqo  ...  2021-07-26T03:43:39Z
2   yY7yau9j3xk  ...  2021-07-20T05:18:03Z
3   i-E4pdU2qXM  ...  2021-07-13T01:34:56Z
4   T1UhSuKqy3A  ...  2021-06-15T05:10:20Z
5   2iE3JgNTwVU  ...  2021-06-04T05:36:49Z
6   RgKMbpEylWA  ...  2021-05-24T05:01:10Z
7   giGIPINLqJs  ...  2021-05-13T06:23:40Z
8   77IVf0zgmwI  ...  2021-05-05T17:55:05Z
9   xtbMCAVXDmU  ...  2021-04-15T10:49:41Z
10  fklHBWow8vE  ...  2021-04-02T03:05:38Z
11  tNXliLTlrV8  ...  2021-03-24T18:30:06Z
12  XRwxYOhHdE8  ...  2021-03-10T18:30:07Z
13  pV_mnZgzXEo  ...  2021-03-03T18:30:05Z
14  c4Af2FcgamA  ...  2021-02-24T18:30:11Z
15  QenwDm5oWdU  ...  2021-02-17T18:30:02Z
16  TYHWv1vT0Pk  ...  2021-02-11T08:00:16Z
17  0GpgMvyN0Fg  ...  2021-02-04T08:00:02Z
18  VYeevsVj4fU  ...  2021-01-27T08:00:17Z
19  vLjAG9eXkcU  ...  2021-01-20T08:00:30Z
20  lG0PbUq4wkg  ...  2021-01-13T08:00:21Z
21  j8kGqAAIhxA  ...  2021-01-06T08:00:09Z
22  W_IERUwElkg  ...  2020-12-28T08:00:18Z
23  eC7MdwKCCOE  ...  2020-12-22T08:00:18Z
24  XBE09l-UYTE  ...  2020-12-17T08:00:16Z
25  C0hk-dZ9XSE  ...  2020-12-10T08:00:02Z
26  N0aHeKyNEto  ...  2020-12-03T08:00:04Z
27  TDwy1lSjEZo  ...  2020-11-24T08:00:08Z
28  EPUayNC5ku4  ...  2020-11-19T08:00:05Z
29  wqBFgaMgFQA  ...  2020-11-15T08:00:10Z
30  IKw0lkmBHNI  ...  2020-11-11T08:00:06Z
31  _gy1o9UH2dQ  ...  2020-11-04T08:00:04Z
32  7Q-2DEwHW7w  ...  2020-10-29T07:00:03Z
33  pFwYjaeKFvQ  ...  2020-10-22T07:00:06Z
34  iR8FDQyCtnw  ...  2020-10-20T07:00:05Z
35  1SgHHQeRuxs  ...  2020-10-18T15:59:35Z
36  UndSRKwsxKM  ...  2020-10-10T07:00:04Z
37  U9P4M4EPTgI  ...  2020-09-23T07:00:04Z
38  S7gKkRxlk1U  ...  2020-09-23T07:00:06Z
39  rMoUoYxfBNk  ...  2020-09-20T07:00:16Z
40  60NaEc7NP_U  ...  2020-09-13T18:19:50Z
41  5-1ClCuQCIw  ...  2020-08-30T20:00:01Z
42  rf2udE9q-SM  ...  2020-08-20T17:20:16Z
43  wqxDfVdZ8wM  ...  2020-08-16T21:00:17Z
44  SrqJuUNN62I  ...  2020-08-08T20:12:00Z
45  -i9chjBSOqU  ...  2020-05-29T17:15:50Z
46  HRzthi_FqAA  ...  2020-05-26T22:53:20Z
47  DUgd48QYmfI  ...  2020-05-26T17:56:05Z

[48 rows x 3 columns]